### ISSUE TITLE
Functionality of the buttons Stack trace and Save results

### ISSUE THREAD

**Issue by alyssonfm** [alyssonfm/contractok#4]
These buttons are not working.

**Comment by ddspog** [comment]
The button Save results was implemented. It's working, but it does not display a message confirming the actions.

**Comment by ddspog** [comment]
The button Save results, after copying files to selected folder, shows a Message dialog confirming sucess of the action.

**Comment by ddspog** [comment]
The button Stack trace, shows MessageBox containing the stack trace of nonconformance selected.
